export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_PROFILE_IMG_CHANGE_REQUEST = "AUTH_PROFILE_IMG_CHANGE_REQUEST";
export const AUTH_PROFILE_IMG_CHANGE_SUCCESS = "AUTH_PROFILE_IMG_CHANGE_SUCCESS";